// ACTION_LISTS ////////////////////////////////////////////////////////////////

export const ADD_BID_PREFIX = "bid/ADD_BID";
export const ADD_BID_REQUEST_ACTION = ADD_BID_PREFIX + "_REQUEST_ACTION";
export const ADD_BID_SUCCESS_ACTION = ADD_BID_PREFIX + "_SUCCESS_ACTION";
export const ADD_BID_FAILURE_ACTION = ADD_BID_PREFIX + "_FAILURE_ACTION";

export const UPDATE_BID_PREFIX = "bid/UPDATE_BID";
export const UPDATE_BID_REQUEST_ACTION = UPDATE_BID_PREFIX + "_REQUEST_ACTION";
export const UPDATE_BID_SUCCESS_ACTION = UPDATE_BID_PREFIX + "_SUCCESS_ACTION";
export const UPDATE_BID_FAILURE_ACTION = UPDATE_BID_PREFIX + "_FAILURE_ACTION";
