// ACTION_LISTS ////////////////////////////////////////////////////////////////
export const GET_ITEMS_PREFIX = "items/GET_ITEMS";
export const GET_ITEMS_REQUEST_ACTION = GET_ITEMS_PREFIX + "_REQUEST_ACTION";
export const GET_ITEMS_SUCCESS_ACTION = GET_ITEMS_PREFIX + "_SUCCESS_ACTION";
export const GET_ITEMS_FAILURE_ACTION = GET_ITEMS_PREFIX + "_FAILURE_ACTION";

export const GET_ITEM_DETAILS_PREFIX = "item/GET_ITEM_DETAILS";
export const GET_ITEM_DETAILS_REQUEST_ACTION =
  GET_ITEM_DETAILS_PREFIX + "_REQUEST_ACTION";
export const GET_ITEM_DETAILS_SUCCESS_ACTION =
  GET_ITEM_DETAILS_PREFIX + "_SUCCESS_ACTION";
export const GET_ITEM_DETAILS_FAILURE_ACTION =
  GET_ITEM_DETAILS_PREFIX + "_FAILURE_ACTION";

export const ADD_ITEM_PREFIX = "items/ADD_ITEM";
export const ADD_ITEM_REQUEST_ACTION = ADD_ITEM_PREFIX + "_REQUEST_ACTION";
export const ADD_ITEM_SUCCESS_ACTION = ADD_ITEM_PREFIX + "_SUCCESS_ACTION";
export const ADD_ITEM_FAILURE_ACTION = ADD_ITEM_PREFIX + "_FAILURE_ACTION";

export const DELETE_ITEM_PREFIX = "items/DELETE_ITEM";
export const DELETE_ITEM_REQUEST_ACTION =
  DELETE_ITEM_PREFIX + "_REQUEST_ACTION";
export const DELETE_ITEM_SUCCESS_ACTION =
  DELETE_ITEM_PREFIX + "_SUCCESS_ACTION";
export const DELETE_ITEM_FAILURE_ACTION =
  DELETE_ITEM_PREFIX + "_FAILURE_ACTION";

export const UPDATE_ITEM_PREFIX = "items/UPDATE_ITEM";
export const UPDATE_ITEM_REQUEST_ACTION =
  UPDATE_ITEM_PREFIX + "_REQUEST_ACTION";
export const UPDATE_ITEM_SUCCESS_ACTION =
  UPDATE_ITEM_PREFIX + "_SUCCESS_ACTION";
export const UPDATE_ITEM_FAILURE_ACTION =
  UPDATE_ITEM_PREFIX + "_FAILURE_ACTION";

export const TOGGLE_MODAL_ACTION = "TOGGLE_MODAL_ACTION";
