export const LOGIN_PREFIX = 'login/LOGIN';
export const LOGIN_PREFIX_REQUEST_ACTION = LOGIN_PREFIX + '_REQUEST_ACTION';
export const LOGIN_PREFIX_SUCCESS_ACTION = LOGIN_PREFIX + '_SUCCESS_ACTION';
export const LOGIN_PREFIX_FAILURE_ACTION = LOGIN_PREFIX + '_FAILURE_ACTION';

export const LOGOUT_PREFIX = 'logout/LOGIN';
export const LOGOUT_PREFIX_REQUEST_ACTION = LOGOUT_PREFIX + '_REQUEST_ACTION';
export const LOGOUT_PREFIX_SUCCESS_ACTION = LOGOUT_PREFIX + '_SUCCESS_ACTION';
export const LOGOUT_PREFIX_FAILURE_ACTION = LOGOUT_PREFIX + '_FAILURE_ACTION';

export const UPDATE_AUTH_DATA_ACTION = 'UPDATE_AUTH_DATA_ACTION';
