export const REGISTER_PREFIX = 'register/GET_CHARTS';
export const REGISTER_PREFIX_REQUEST_ACTION = REGISTER_PREFIX + '_REQUEST_ACTION';
export const REGISTER_PREFIX_SUCCESS_ACTION = REGISTER_PREFIX + '_SUCCESS_ACTION';
export const REGISTER_PREFIX_FAILURE_ACTION = REGISTER_PREFIX + '_FAILURE_ACTION';
